### ISSUE TITLE
Лишняя часть в типе источника "Веб-узел"

### ISSUE THREAD

**Issue by Homer68Rus** [irandom/docs#10]
В объекте type="InternetSite" в строках 332 и 333

<format lcid="1033">{%Author:249%.}{ %Title% [Электронный ресурс]}{ // %InternetSiteTitle%: [сайт].}{ [%Year%].}{ URL: %URL:0s%}{ (дата обращения: %DayAccessed%.%MonthAccessed%.%YearAccessed%).}</format>
<format lcid="1049">{%Author:249%.}{ %Title% [Электронный ресурс]}{ // %InternetSiteTitle%: [сайт].}{ [%Year%].}{ URL: %URL:0s%}{ (дата обращения: %DayAccessed%.%MonthAccessed%.%YearAccessed%).}</format>

используются параметры {%Author:249%.} и { %Title% [Электронный ресурс]}, которых нет в этом объекте (они есть в объекте "Документ с веб-узла").
Поэтому, при создании такого типа в Word в списке литературы строка начинается с " // " из-за того, что {%Author:249%.}{ %Title% [Электронный ресурс]} пустое, а в { // %InternetSiteTitle%: [сайт].} как раз присутствует двойной слеш.
Необходимо заменить строки на

<format lcid="1033">{%InternetSiteTitle%: [сайт].}{ [%Year%].}{ URL: %URL:0s%}{ (дата обращения: %DayAccessed%.%MonthAccessed%.%YearAccessed%).}</format>
<format lcid="1049">{%InternetSiteTitle%: [сайт].}{ [%Year%].}{ URL: %URL:0s%}{ (дата обращения: %DayAccessed%.%MonthAccessed%.%YearAccessed%).}</format>

то есть убрать два параметра, которых нет, а также убрать двойной слеш.

**Comment by MFedyukov** [comment]
Не совсем так.
В InternetSite есть и Author, и Title.
Чтобы отобразить (и заполнить) их в Word, надо в окне «Изменить источник» нажать «Показать все поля списка литературы».
В ГОСТ Р 7.0.5—2008 (https://ru.wikisource.org/wiki/ГОСТ_Р_7.0.5—2008) в разделе «Особенности составления библиографических ссылок на электронные ресурсы» также нет ограничений на упоминание авторов как в ссылках на _составные части электронных ресурсов (разделы и части электронных документов, порталов, сайтов, веб-страниц...),_ так и в ссылках на _электронные ресурсы в целом (электронные документы, базы данных, порталы, сайты, веб-страницы...)._
Соответственно, правильно было бы не удалять элементы Author и Title, а сделать поле Title отображаемым в окне «Изменить источник» по умолчанию.
Для этого надо в `<source type="InternetSite">` добавить `<b:ImportantField>b:Title</b:ImportantField>`.

**Comment by irandom** [comment]
Исправлено в bb3e9acc60962e400701175017c28c072f011da0
