### ISSUE TITLE
Не хватает пробела после запятой в отсылках

### ISSUE THREAD

**Issue by MFedyukov** [irandom/docs#11]
В соответствии с правилами русского языка после запятых и точек с запятой должен стоять пробел (http://orfogrammka.ru/оформление/пробел_и_знаки_пунктуации/), что также соблюдается во всех примерах в ГОСТ Р 7.0.5—2008 (https://ru.wikisource.org/wiki/ГОСТ_Р_7.0.5—2008):
> [10, с. 81]
> [Пахомов, Петрова]
> [Бахтин, 2003, с. 18]
> [Сергеев, Латышев, 2001; Сергеев, Крохин, 2000]

В текущих же xsl-файлах не хватает запятой:
```<citation>
       <openbracket>[</openbracket>
       <closebracket>]</closebracket>
       <separator>,</separator>
       ...
```

В результате отсылки выглядят так:
> [36,37,38,39],

но должны выглядеть так:

> [36, 37, 38, 39].

**Comment by irandom** [comment]
Исправлено в bb3e9acc60962e400701175017c28c072f011da0
