### ISSUE TITLE
В некоторых типах источников встречаются «и» и «and»

### ISSUE THREAD

**Issue by MFedyukov** [irandom/docs#12]
Но союзов быть не должно, должны быть просто запятые:
> 7.5.1. Если ссылку приводят на документ, созданный одним, двумя или тремя авторами, в отсылке указывают фамилии авторов, если на документ, созданный четырьмя и более авторами, а также, если авторы не указаны, — в отсылке указывают название документа; при необходимости сведения дополняют указанием года издания и страниц. **Сведения в отсылке разделяют запятой.**

**Comment by MFedyukov** [comment]
В ГОСТ Р 7.0.5—2008 (https://ru.wikisource.org/wiki/ГОСТ_Р_7.0.5—2008) все примеры без «и».

**Comment by irandom** [comment]
Исправлено в bb3e9acc60962e400701175017c28c072f011da0
