### ISSUE TITLE
Поддержка Office 2016 | Office 2016 support

### ISSUE THREAD

**Issue by Kenya-West** [irandom/docs#16]
Реализована ли поддержка Office 2016? Боюсь применять это на своей дипломной.

Does it support Office 2016? I afraid if this broke my diploma...

**Comment by PASAf** [comment]
@Kenya-West Можно сделать резервную копию.
И да, реализована. Покрайней мере у меня всё на новом документе функционирует.

**Comment by Kenya-West** [comment]
Подтверждаю, я с вашим продуктом работал три месяца на своей дипломной в "продакшене". Всё идеально работает.

Один нюанс: при очередном добавлении пункта литературы нужно заново произвести манипуляции с BiblWord Extender, чтобы список литературы вновь отсортировался по имени.

**Comment by irandom** [comment]
О, пока меня не было, задачу и создали и разрешили:) Закрываю тогда:)
