### ISSUE TITLE
Установка под MS word 2016 

### ISSUE THREAD

**Issue by uncle-khmel** [irandom/docs#18]
Доброго дня!
Уважаемые коллеги, нужна помощь. При попытке установить ваш стиль 7-2008, сделал все как  написано .

 Однако в выпадающем списке стилей списков изменений  не произошло.
Помогите, пожалуйста, разобраться. 

![2016-10-27_10-59-17](https://cloud.githubusercontent.com/assets/14905567/19759464/d4998cdc-9c35-11e6-90b5-50bcfc6d3efb.png)

**Comment by irandom** [comment]
Вот здесь в комментариях нет ли решения, случайно? http://det-random.livejournal.com/28819.html

**Comment by irandom** [comment]
Может также поинтересоваться у участников #16, каким способом они всё настроили. Если удастся решить проблему, то напишите об этом сюда тоже, плиз.

**Comment by uncle-khmel** [comment]
Спасибо.  буду разбираться 

Отправлено с iPhone

**Comment by uncle-khmel** [comment]
Доброго, пока разбираюсь. на VM c win 10 под 
![2016-10-28_11-15-22](https://cloud.githubusercontent.com/assets/14905567/19799583/270e86dc-9d00-11e6-881f-3ea4c24bd0cb.png)
Office 2016 запускается

**Comment by irandom** [comment]
@uncle-khmel А на настоящей машине удалось добавить стиль?

**Comment by irandom** [comment]
Если не будет работать, можно переоткрыть тикет.

**Comment by uncle-khmel** [comment]
Шаманство, какое-то 

, НО ЗАРАБОТАЛО  :):):)  под win7 64 pro 
СПАСИБО

![2016-11-07_9-45-01](https://cloud.githubusercontent.com/assets/14905567/20048639/24e66b28-a4cf-11e6-937d-cacfd8b76076.png)

**Comment by korshun1983** [comment]
Приветствую!

А в чем шаманство состоит? У меня Office 365 (Word 16). Скопировал стилевой файл в 
C:\Program Files\Microsoft Office\root\Office16\Bibliography\Style
и
C:\Users\user\AppData\Roaming\Microsoft\Bibliography\Style

а в Word так ничего и не видно.

на ЖЖ читал все комменты, но так и не понял, надо ли что-то исправлять в стилевом файле. 
Помогите разобраться, пожалуйста!

**Comment by djbond07** [comment]
> Шаманство, какое-то
> 
> , НО ЗАРАБОТАЛО :):):) под win7 64 pro
> СПАСИБО
> 
> ![2016-11-07_9-45-01](https://cloud.githubusercontent.com/assets/14905567/20048639/24e66b28-a4cf-11e6-937d-cacfd8b76076.png)

Добрый день! 
Подскажите как удалось запустить в word 2016?
