### ISSUE TITLE
Поиск списков литературы 

### ISSUE THREAD

**Issue by uncle-khmel** [irandom/docs#19]
Доброго дня!
Коллеги, известны ли вам базы, таблицы, списки литературы, которые бы можно было использовать, а не составлять все перечни, федеральных законов, гостов, постановлений, диссертаций с нуля.
Найти такое сокровище пока не удалось :(

**Comment by MFedyukov** [comment]
Список литературы хранится в виде xml-файла. Соответственно, если есть
нужные перечни в ином формате, можно сконвертировать их в xml, хотя бы
через тот же Excel.

**Comment by irandom** [comment]
Кажется, к такому перечню потребуется приложение, которое будет им управлять, потому что объемы должны быть огромными. Кажется, Консультант Плюс берет деньги не зря.

Тикет закрою, так как непосредственно к разработке стиля он не относится.
