### ISSUE TITLE
Отсутствие точек в ФИО в «патенте»

### ISSUE THREAD

**Issue by MFedyukov** [irandom/docs#6]
В версии gost-r-7.0.5-2008 от Jun 13, 2014 в Word 2010 есть неточность – ФИО не содержит точек.
Так, например, запись с авторами "Парк, И. К.; Чох, Х. К.; Вежневец, В. П.; Жанг, Х." в Списке литературы выглядит следующим образом:
Парк ИК и др., "Method and apparatus for image-based photorealistic 3D face modeling," Патент № 7835568, 2005

**Comment by MFedyukov** [comment]
Проблема отсутствия точек также присутствует в ряде других типов (все – `<!-- not implemented -->`).
Решается заменой `Author:133%` на `Author:233%` (т. е., использованием `<list name="author" id="233">` вместо `<list name="citation" id="133">`).

**Comment by irandom** [comment]
Исправлено в bb3e9acc60962e400701175017c28c072f011da0
