### ISSUE TITLE
Поддержка Office 2013

### ISSUE THREAD

**Issue by paulvonlecter** [irandom/docs#9]
На компьютере установлена Windows 8.1 (with Media Center) с Office 2013 на борту.
Офис не крякнутый, ОСь тоже.
При попытке просмотра/редактирования списка литературы в окне вылезает таблица, где во втором столбце через пробел указаны заполненные поля (Заглавие, Автор и блаблабла..)
При вставке ссылки в документ, ничего большего чем [] вставить не удается.
А при вставке списка литературы, вставляется вышеназванная таблица.
Пожалуйста, разрешите эту проблему совместимости, а то плохо дела х(
P.S. У меня нет квалификации работы с XSL. Так бы поправил.

**Comment by irandom** [comment]
Добрый день. К сожалению, у меня нет лицензии на офис 2013 и Windows 8.1, так что могу только предложить подождать, пока кто-то не наткнется на этот тикет и не поправит его. Конечно, если у вас есть терминальный сервер с нужным окружением, мне было бы проще, но надежда на это слаба:)

**Comment by DrZugrik** [comment]
У меня такая же проблема(( Windows 7, Office 2013. Ссылки вставляются в виде [], а в списке литературы нет нумерации, список литературы не обновляется...

**Comment by irandom** [comment]
@paulvonlecter @DrZugrik А если попробовать рецепты из комментариев к http://det-random.livejournal.com/28819.html ?

**Comment by irandom** [comment]
Вполне возможно, необходимость отпала, все-таки февраль 2015. Закрою тикет, его всегда можно переоткрыть.
